# Generated by Django 4.2.7 on 2026-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_add_route_deviation_exception'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatcherexceptionaction',
            new_name='dispatcher__dispatc_9bfa4b_idx',
            old_name='dispatcher_e_dispatc_4f7ec6_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatcherexceptionaction',
            new_name='dispatcher__snoozed_1a4349_idx',
            old_name='dispatcher_e_snoozed_0e5122_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatcherexceptionaction',
            new_name='dispatcher__acknowl_ac2673_idx',
            old_name='dispatcher_e_acknowl_35a06e_idx',
        ),
    ]
