# Generated by Django 4.2.7 on 2026-04-09 12:02

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_add_route_deviation_exception'),
    ]

    operations = [
        rename_index_operation(
            'dispatcherexceptionaction',
            'dispatcher_e_dispatc_4f7ec6_idx',
            'dispatcher__dispatc_9bfa4b_idx',
        ),
        rename_index_operation(
            'dispatcherexceptionaction',
            'dispatcher_e_snoozed_0e5122_idx',
            'dispatcher__snoozed_1a4349_idx',
        ),
        rename_index_operation(
            'dispatcherexceptionaction',
            'dispatcher_e_acknowl_35a06e_idx',
            'dispatcher__acknowl_ac2673_idx',
        ),
    ]
