# Generated by Django 4.2.7 on 2026-06-12 11:37

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_preferences_and_push_queue'),
    ]

    operations = [
        rename_index_operation(
            'pushdeliveryqueue',
            'push_deliv_status_idx',
            'push_delive_status_1426fd_idx',
        ),
        rename_index_operation(
            'pushdeliveryqueue',
            'push_deliv_user_status_idx',
            'push_delive_user_id_792ed0_idx',
        ),
    ]
