# Generated by Django 4.2.7 on 2026-06-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_preferences_and_push_queue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdeliveryqueue',
            new_name='push_delive_status_1426fd_idx',
            old_name='push_deliv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliveryqueue',
            new_name='push_delive_user_id_792ed0_idx',
            old_name='push_deliv_user_status_idx',
        ),
    ]
