# Generated by Django 4.2.7 on 2026-06-11 08:24

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_complaint'),
    ]

    operations = [
        rename_index_operation(
            'complaint',
            'complaints_to_user_8b0f0d_idx',
            'complaints_to_user_39a447_idx',
        ),
        rename_index_operation(
            'complaint',
            'complaints_from_us_6a8c2e_idx',
            'complaints_from_us_20ccf9_idx',
        ),
    ]
