# Generated by Django 4.2.7 on 2026-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_complaint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints_to_user_39a447_idx',
            old_name='complaints_to_user_8b0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints_from_us_20ccf9_idx',
            old_name='complaints_from_us_6a8c2e_idx',
        ),
    ]
