# Generated by Django 4.2.7 on 2026-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rename_complaints_to_user_8b0f0d_idx_complaints_to_user_39a447_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('order', 'from_user', 'to_user'), name='unique_complaint_per_order_party'),
        ),
    ]
