# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
     "react-native/scripts/react_native_pods.rb",
     { paths: [process.argv[1]] },
   )',
   __dir__
  ]
).strip

platform :ios, min_ios_version_supported

use_modular_headers!

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Logistika' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # MapLibre Native SDK (Swift Package Manager)
    $MLRN.post_install(installer)

    # Apple Silicon simulator: arm64 ni exclude qilmaslik kerak.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      end
    end

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |build_config|
          build_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end

    Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', 'Pods-*', '*.xcconfig')).each do |xcconfig|
      contents = File.read(xcconfig)
      patched = contents.gsub(
        'EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64',
        'EXCLUDED_ARCHS[sdk=iphonesimulator*] = i386'
      )
      File.write(xcconfig, patched) if patched != contents
    end
  end
end
