# Generated by Django 4.2.7 on 2026-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatcher_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dispatcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_updater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updater_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
