# Generated by Django 4.2.7 on 2026-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dispatcher_code_user_is_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token', max_length=255, null=True),
        ),
    ]
