# Generated by Django 4.2.7 on 2026-04-09 12:19

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverdocument'),
    ]

    operations = [
        rename_index_operation(
            'driverdocument',
            'driver_docum_user_id_83fefd_idx',
            'driver_docu_user_id_0335c7_idx',
        ),
        rename_index_operation(
            'driverdocument',
            'driver_docum_expires_16d92c_idx',
            'driver_docu_expires_41d3e7_idx',
        ),
        rename_index_operation(
            'driverdocument',
            'driver_docum_is_acti_f7f5f5_idx',
            'driver_docu_is_acti_f7f7d2_idx',
        ),
    ]
