# Generated by Django 4.2.7 on 2026-04-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverdocument',
            new_name='driver_docu_user_id_0335c7_idx',
            old_name='driver_docum_user_id_83fefd_idx',
        ),
        migrations.RenameIndex(
            model_name='driverdocument',
            new_name='driver_docu_expires_41d3e7_idx',
            old_name='driver_docum_expires_16d92c_idx',
        ),
        migrations.RenameIndex(
            model_name='driverdocument',
            new_name='driver_docu_is_acti_f7f7d2_idx',
            old_name='driver_docum_is_acti_f7f5f5_idx',
        ),
    ]
