# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_verification_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_driv_216ab3_idx',
            old_name='users_driver_verif_idx',
        ),
    ]
