# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_verification_status'),
    ]

    operations = [
        rename_index_operation(
            'user',
            'users_driver_verif_idx',
            'users_is_driv_216ab3_idx',
        ),
    ]
