# Generated by Django 4.2.7 on 2026-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_users_driver_verif_idx_users_is_driv_216ab3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
