# Generated by Django 4.2.7 on 2026-08-13 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def copy_legacy_fcm_tokens(apps, schema_editor):
    User = apps.get_model('users', 'User')
    DeviceFcmToken = apps.get_model('users', 'DeviceFcmToken')
    now = timezone.now()
    seen = set(DeviceFcmToken.objects.values_list('token', flat=True))
    rows = []
    for user in User.objects.exclude(fcm_token__isnull=True).exclude(fcm_token='').iterator():
        token = (user.fcm_token or '').strip()[:512]
        if not token or token in seen:
            continue
        seen.add(token)
        rows.append(
            DeviceFcmToken(
                user_id=user.id,
                token=token,
                device_id='',
                platform='unknown',
                is_active=True,
                last_seen_at=now,
                created_at=now,
                updated_at=now,
            )
        )
    if rows:
        DeviceFcmToken.objects.bulk_create(rows, batch_size=500)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_company_payout_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(
                blank=True,
                help_text='Last-known FCM token (legacy fallback; devices live in DeviceFcmToken)',
                max_length=512,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='DeviceFcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_fcm_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_fcm__user_id_c8da3a_idx'), models.Index(fields=['device_id'], name='device_fcm__device__71bb3e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='devicefcmtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id', ''), _negated=True), fields=('user', 'device_id'), name='uniq_active_device_token_per_user'),
        ),
        migrations.RunPython(copy_legacy_fcm_tokens, noop_reverse),
    ]
