from django.db import migrations


def rename_index_if_exists(old_name: str, new_name: str):
    """Rename a PostgreSQL index only when the old name is present.

    Fresh databases (and DBs that never had the autogenerated name) would
    otherwise crash on Django's RenameIndex.
    """
    return migrations.RunSQL(
        sql=f"""
        DO $$
        BEGIN
            IF to_regclass('{old_name}') IS NOT NULL AND to_regclass('{new_name}') IS NULL THEN
                EXECUTE 'ALTER INDEX "{old_name}" RENAME TO "{new_name}"';
            END IF;
        END
        $$;
        """,
        reverse_sql=f"""
        DO $$
        BEGIN
            IF to_regclass('{new_name}') IS NOT NULL AND to_regclass('{old_name}') IS NULL THEN
                EXECUTE 'ALTER INDEX "{new_name}" RENAME TO "{old_name}"';
            END IF;
        END
        $$;
        """,
    )


def rename_index_operation(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[rename_index_if_exists(old_name, new_name)],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                new_name=new_name,
                old_name=old_name,
            ),
        ],
    )
