# Generated by Django 4.2.7 on 2026-01-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('public_offer', 'Public Offer'), ('disclaimer', 'Disclaimer'), ('guide_clients', 'Guide for Clients'), ('guide_drivers', 'Guide for Drivers'), ('settings', 'Settings')], max_length=20, unique=True)),
                ('content_ru', models.TextField()),
                ('content_en', models.TextField()),
                ('content_uz', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Content',
                'verbose_name_plural': 'Static Contents',
                'db_table': 'static_content',
            },
        ),
    ]
