from django.urls import path
from .views import (
    DispatcherDashboardView,
    DispatcherOrdersView,
    DispatcherOrderDetailView,
    DispatcherAssignView,
    DispatcherReassignView,
    DispatcherCancelOrderView,
    DispatcherAddNoteView,
    DispatcherDriversView,
    DispatcherClientsView,
    DispatcherStatisticsView,
    DispatcherDriverDetailView,
    DispatcherClientDetailView,
    DispatcherOrdersMapView,
    DispatcherDriverOrdersView,
    DispatcherClientOrdersView,
    DispatcherAnalyticsView,
    DispatcherBulkOperationsView,
    DispatcherExportView,
    DispatcherMonitoringView,
    DispatcherExceptionAcknowledgeView,
    DispatcherExceptionSnoozeView,
    DispatcherSuggestionsAssignView,
    DispatcherAllDriversLocationView,
    DispatcherAllOrdersStatusView,
)

app_name = 'dispatcher'

urlpatterns = [
    path('dashboard/', DispatcherDashboardView.as_view(), name='dashboard'),
    path('orders/', DispatcherOrdersView.as_view(), name='orders'),
    path('orders/map/', DispatcherOrdersMapView.as_view(), name='orders-map'),
    path('orders/<int:pk>/', DispatcherOrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/assign/', DispatcherAssignView.as_view(), name='assign'),
    path('orders/<int:pk>/reassign/', DispatcherReassignView.as_view(), name='reassign'),
    path('orders/<int:pk>/cancel/', DispatcherCancelOrderView.as_view(), name='cancel'),
    path('orders/<int:pk>/note/', DispatcherAddNoteView.as_view(), name='add-note'),
    path('drivers/', DispatcherDriversView.as_view(), name='drivers'),
    path('drivers/<int:driver_id>/', DispatcherDriverDetailView.as_view(), name='driver-detail'),
    path('drivers/<int:driver_id>/orders/', DispatcherDriverOrdersView.as_view(), name='driver-orders'),
    path('clients/', DispatcherClientsView.as_view(), name='clients'),
    path('clients/<int:client_id>/', DispatcherClientDetailView.as_view(), name='client-detail'),
    path('clients/<int:client_id>/orders/', DispatcherClientOrdersView.as_view(), name='client-orders'),
    path('statistics/', DispatcherStatisticsView.as_view(), name='statistics'),
    path('analytics/', DispatcherAnalyticsView.as_view(), name='analytics'),
    path('bulk-operations/', DispatcherBulkOperationsView.as_view(), name='bulk-operations'),
    path('export/', DispatcherExportView.as_view(), name='export'),
    path('monitoring/', DispatcherMonitoringView.as_view(), name='monitoring'),
    path('exceptions/ack/', DispatcherExceptionAcknowledgeView.as_view(), name='exception-ack'),
    path('exceptions/snooze/', DispatcherExceptionSnoozeView.as_view(), name='exception-snooze'),
    path('suggestions/assign/', DispatcherSuggestionsAssignView.as_view(), name='suggestions-assign'),
    path('drivers/locations/', DispatcherAllDriversLocationView.as_view(), name='drivers-locations'),
    path('orders/status/', DispatcherAllOrdersStatusView.as_view(), name='orders-status'),
]
