# Generated by Django 4.2.7 on 2026-01-09 11:14

from django.db import migrations


def create_default_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    
    statuses = [
        {
            'code': 'new',
            'name_ru': 'Новый',
            'name_en': 'New',
            'name_uz': 'Yangi'
        },
        {
            'code': 'pending',
            'name_ru': 'Ожидание',
            'name_en': 'Pending',
            'name_uz': 'Kutilmoqda'
        },
        {
            'code': 'in_progress',
            'name_ru': 'В процессе',
            'name_en': 'In Progress',
            'name_uz': 'Jarayonda'
        },
        {
            'code': 'stopped',
            'name_ru': 'Остановлен',
            'name_en': 'Stopped',
            'name_uz': 'To\'xtatilgan'
        },
        {
            'code': 'completed',
            'name_ru': 'Завершен',
            'name_en': 'Completed',
            'name_uz': 'Yakunlangan'
        },
        {
            'code': 'rejected',
            'name_ru': 'Отклонен',
            'name_en': 'Rejected',
            'name_uz': 'Rad etilgan'
        }
    ]
    
    for status_data in statuses:
        OrderStatus.objects.get_or_create(
            code=status_data['code'],
            defaults={
                'name_ru': status_data['name_ru'],
                'name_en': status_data['name_en'],
                'name_uz': status_data['name_uz']
            }
        )


def reverse_create_default_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    OrderStatus.objects.filter(
        code__in=['new', 'pending', 'in_progress', 'stopped', 'completed', 'rejected']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_statuses, reverse_create_default_statuses),
    ]
