# Generated by Django 4.2.7 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pod_and_route_deviation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_at'], name='orders_client__bc22a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'created_at'], name='orders_driver__269869_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status__e657e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['advertisement'], name='orders_adverti_268847_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
    ]
