# Generated by Django 4.2.7 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_returns_quality_and_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_app_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
