# Generated by Django 4.2.7 on 2026-06-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_multistop_routing_and_track_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderlocationtrack',
            new_name='order_locat_order_i_4dc17d_idx',
            old_name='order_locat_order_i_idx',
        ),
        migrations.RenameIndex(
            model_name='orderlocationtrack',
            new_name='order_locat_timesta_d65743_idx',
            old_name='order_locat_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='orderroutestop',
            new_name='order_route_order_i_91b0be_idx',
            old_name='order_route_order_i_idx',
        ),
    ]
