# Generated by Django 4.2.7 on 2026-06-12 11:37

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_multistop_routing_and_track_indexes'),
    ]

    operations = [
        rename_index_operation(
            'orderlocationtrack',
            'order_locat_order_i_idx',
            'order_locat_order_i_4dc17d_idx',
        ),
        rename_index_operation(
            'orderlocationtrack',
            'order_locat_timesta_idx',
            'order_locat_timesta_d65743_idx',
        ),
        rename_index_operation(
            'orderroutestop',
            'order_route_order_i_idx',
            'order_route_order_i_91b0be_idx',
        ),
    ]
