# Generated by Django 4.2.7 on 2026-08-13 15:26

import apps.orders.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_live_motion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Hisob-faktura'), ('ttn', 'TTN / yuk xati'), ('act', 'Bajarilgan ishlar dalolatnomasi')], max_length=20)),
                ('number', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('html_file', models.FileField(blank=True, upload_to=apps.orders.models.order_document_upload_to)),
                ('xlsx_file', models.FileField(blank=True, upload_to=apps.orders.models.order_document_upload_to)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
            ],
            options={
                'db_table': 'order_documents',
                'ordering': ['doc_type'],
                'unique_together': {('order', 'doc_type')},
                'indexes': [
                    models.Index(fields=['order', 'doc_type'], name='order_docum_order_i_2fca96_idx'),
                    models.Index(fields=['download_token'], name='order_docum_downloa_fa891d_idx'),
                ],
            },
        ),
    ]
