# Generated by Django 4.2.7 on 2026-08-14 11:51

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_execution_gates'),
    ]

    operations = [
        rename_index_operation(
            'ordercustodyevent',
            'order_custo_order_i_6f0a2a_idx',
            'order_custo_order_i_940b0c_idx',
        ),
        rename_index_operation(
            'ordercustodyevent',
            'order_custo_event_t_0f2f0d_idx',
            'order_custo_event_t_44895c_idx',
        ),
        rename_index_operation(
            'ordersosalert',
            'order_sos_a_status_2f0f0d_idx',
            'order_sos_a_status_502a07_idx',
        ),
        rename_index_operation(
            'ordersosalert',
            'order_sos_a_order_i_0f0f0d_idx',
            'order_sos_a_order_i_b8b66d_idx',
        ),
    ]
