# Generated by Django 4.2.7 on 2026-08-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_execution_gates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordercustodyevent',
            new_name='order_custo_order_i_940b0c_idx',
            old_name='order_custo_order_i_6f0a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='ordercustodyevent',
            new_name='order_custo_event_t_44895c_idx',
            old_name='order_custo_event_t_0f2f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersosalert',
            new_name='order_sos_a_status_502a07_idx',
            old_name='order_sos_a_status_2f0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersosalert',
            new_name='order_sos_a_order_i_b8b66d_idx',
            old_name='order_sos_a_order_i_0f0f0d_idx',
        ),
    ]
