# Generated by Django 4.2.7 on 2026-06-11 08:24

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_marketplace_trial'),
    ]

    operations = [
        rename_index_operation(
            'usersubscription',
            'user_subscr_user_id_0f0f0d_idx',
            'user_subscr_user_id_a34786_idx',
        ),
    ]
