# Generated by Django 4.2.7 on 2026-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_marketplace_trial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='user_subscr_user_id_a34786_idx',
            old_name='user_subscr_user_id_0f0f0d_idx',
        ),
    ]
