# Generated by Django 4.2.7 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_contact_name_message_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['client', 'updated_at'], name='chats_client__7bd84a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['driver', 'updated_at'], name='chats_driver__a5af2a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['order'], name='chats_order_i_f1f758_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['updated_at'], name='chats_updated_9a6675_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='messages_chat_id_ec31ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messages_sender__bf8b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messages_created_919c58_idx'),
        ),
    ]
