# Generated by Django 4.2.7 on 2026-01-09 10:47

from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    Advertisement = apps.get_model('advertisements', 'Advertisement')
    for ad in Advertisement.objects.all():
        if ad.title:
            ad.title_ru = ad.title
            ad.title_en = ad.title
            ad.title_uz = ad.title
        if ad.description:
            ad.description_ru = ad.description
            ad.description_en = ad.description
            ad.description_uz = ad.description
        ad.save()


def migrate_data_backward(apps, schema_editor):
    Advertisement = apps.get_model('advertisements', 'Advertisement')
    for ad in Advertisement.objects.all():
        if ad.title_ru:
            ad.title = ad.title_ru
        if ad.description_ru:
            ad.description = ad.description_ru
        ad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
