# Generated by Django 4.2.7 on 2026-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_uz',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_uz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
