# Generated by Django 4.2.7 on 2026-02-10 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('advertisements', '0005_alter_advertisement_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementexecution',
            options={'verbose_name': 'Advertisement Execution', 'verbose_name_plural': 'Advertisement Executions'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='departure_country',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='height',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='is_fragile',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='length',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='width',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='currency',
            field=models.CharField(default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='advertisementexecution',
            name='proposed_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='departure_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_advertisements', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='destination_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_advertisements', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='advertisementexecution',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementexecution',
            unique_together={('advertisement', 'driver')},
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches_departure', to='locations.city')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches_destination', to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_searches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='advertisementexecution',
            name='client',
        ),
        migrations.RemoveField(
            model_name='advertisementexecution',
            name='is_rejected_by_driver',
        ),
        migrations.CreateModel(
            name='FavoriteAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Advertisement',
                'verbose_name_plural': 'Favorite Advertisements',
                'db_table': 'favorite_advertisements',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'advertisement')},
            },
        ),
    ]
