# Generated by Django 4.2.7 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisementexecution_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['client', 'is_closed', 'created_at'], name='advertiseme_client__d7fe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['departure_city', 'destination_city', 'is_closed'], name='advertiseme_departu_31dbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_closed', 'created_at'], name='advertiseme_is_clos_aaf657_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['created_at'], name='advertiseme_created_dcafdd_idx'),
        ),
    ]
