# Generated by Django 4.2.7 on 2026-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_advertisement_advertiseme_client__d7fe8f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cargo_category',
            field=models.CharField(choices=[('general', 'General'), ('furniture', 'Furniture'), ('food', 'Food'), ('electronics', 'Electronics'), ('construction', 'Construction'), ('documents', 'Documents'), ('fragile', 'Fragile'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='delivery_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pickup_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pickup_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='route_preference',
            field=models.CharField(choices=[('fastest', 'Fastest'), ('cheapest', 'Cheapest'), ('balanced', 'Balanced'), ('no_toll', 'No Toll')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='special_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='units_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
