# Generated by Django 4.2.7 on 2026-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_advertisement_cargo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='route_stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
