# Generated by Django 4.2.7 on 2026-08-14 11:51

from django.db import migrations

from apps.common.migration_ops import rename_index_operation


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_driverlane_time_window'),
    ]

    operations = [
        rename_index_operation(
            'driverlane',
            'driver_lane_user_id_is_act_idx',
            'driver_lane_user_id_d14cb6_idx',
        ),
    ]
