# Generated by Django 4.2.7 on 2026-08-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_driverlane_time_window'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverlane',
            new_name='driver_lane_user_id_d14cb6_idx',
            old_name='driver_lane_user_id_is_act_idx',
        ),
    ]
