# Generated by Django 4.2.7 on 2026-01-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver_agreed_to_amount', models.BooleanField(default=False)),
                ('proposed_amounts', models.JSONField(blank=True, default=list)),
                ('is_rejected_by_client', models.BooleanField(default=False)),
                ('is_accepted_by_client', models.BooleanField(default=False)),
                ('is_rejected_by_driver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table': 'bids',
                'ordering': ['-created_at'],
            },
        ),
    ]
