import { StyleSheet, Dimensions } from 'react-native';
import type { AppColors } from '../../theme/colors';
import { spacing, borderRadius, fontSize, fontWeight, shadows } from '../../theme';

export function createDispatcherMonitoringStyles(colors: AppColors, screenHeight?: number) {
  const height = screenHeight ?? Dimensions.get('window').height;

  return StyleSheet.create({
    container: {
      flex: 1,
    },
    selectedStatsCard: {
      marginTop: spacing.sm,
      marginVertical: spacing.sm,
    },
    selectedStatsTitle: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.sm,
    },
    openOrderBtn: {
      marginTop: spacing.sm,
      alignSelf: 'flex-start',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: `${colors.primary}22`,
    },
    openOrderBtnText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    header: {
      maxHeight: height * 0.62,
    },
    headerContent: {
      padding: spacing.lg,
      paddingBottom: spacing.lg,
    },
    healthRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    sosSection: {
      marginBottom: spacing.md,
    },
    healthPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.round,
      borderWidth: 1,
    },
    healthPillGood: {
      backgroundColor: colors.successGlow,
      borderColor: `${colors.success}55`,
    },
    healthPillBad: {
      backgroundColor: colors.dangerGlow,
      borderColor: `${colors.danger}55`,
    },
    healthDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    healthPillText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
    },
    healthPillTextGood: {
      color: colors.success,
    },
    healthPillTextBad: {
      color: colors.danger,
    },
    healthPillNeutral: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.round,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    healthPillTextNeutral: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.textSecondary,
    },
    statsRow: {
      flexDirection: 'row',
      gap: spacing.md,
      marginBottom: spacing.lg,
    },
    statCard: {
      flex: 1,
      alignItems: 'center',
      marginVertical: 0,
    },
    statIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statValue: {
      fontSize: fontSize.xxl,
      fontWeight: fontWeight.extrabold,
      color: colors.text,
      marginTop: spacing.sm,
      letterSpacing: -0.5,
    },
    statLabel: {
      fontSize: fontSize.sm,
      color: colors.textTertiary,
      marginTop: 4,
      fontWeight: fontWeight.semibold,
      textAlign: 'center',
    },
    exceptionsCard: {
      marginBottom: spacing.lg,
      marginVertical: spacing.sm,
    },
    exceptionsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
      gap: spacing.sm,
    },
    exceptionsTitle: {
      flex: 1,
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: colors.text,
    },
    exceptionsCount: {
      fontSize: fontSize.base,
      fontWeight: fontWeight.extrabold,
      color: colors.danger,
    },
    exceptionsSubtext: {
      fontSize: fontSize.sm,
      color: colors.textTertiary,
      lineHeight: 18,
    },
    metricRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    metricChip: {
      minWidth: 72,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: colors.borderLight,
      alignItems: 'center',
    },
    metricChipValue: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.extrabold,
      color: colors.text,
    },
    metricChipLabel: {
      marginTop: 2,
      fontSize: fontSize.xs,
      color: colors.textTertiary,
      fontWeight: fontWeight.bold,
    },
    filterSectionTitle: {
      marginTop: spacing.sm,
      marginBottom: 2,
      fontSize: fontSize.xs,
      fontWeight: fontWeight.extrabold,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    routeDeviationBanner: {
      marginTop: spacing.sm,
      borderRadius: borderRadius.md,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      backgroundColor: colors.dangerGlow,
      borderWidth: 1,
      borderColor: `${colors.danger}44`,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    routeDeviationBannerText: {
      flex: 1,
      fontSize: fontSize.sm,
      color: colors.text,
      fontWeight: fontWeight.bold,
    },
    filterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: spacing.sm,
    },
    filterChip: {
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.round,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      ...shadows.colored(colors.primaryDark),
    },
    filterChipText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.textSecondary,
    },
    filterChipTextActive: {
      color: colors.textLight,
    },
    resetFiltersButton: {
      marginTop: spacing.sm,
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: `${colors.primary}22`,
    },
    resetFiltersText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    viewModeButtons: {
      flexDirection: 'row',
      gap: spacing.md,
      marginTop: spacing.sm,
    },
    liveBar: {
      marginTop: spacing.sm,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    liveText: {
      fontSize: fontSize.sm,
      color: colors.textTertiary,
      fontWeight: fontWeight.semibold,
    },
    followButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.round,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    followButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    followButtonText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.textSecondary,
    },
    followButtonTextActive: {
      color: colors.textLight,
    },
    wsBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.round,
      borderWidth: 1,
    },
    wsBadgeOnline: {
      backgroundColor: colors.successGlow,
      borderColor: `${colors.success}55`,
    },
    wsBadgeOffline: {
      backgroundColor: colors.dangerGlow,
      borderColor: `${colors.danger}55`,
    },
    wsDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    wsDotOnline: {
      backgroundColor: colors.success,
    },
    wsDotOffline: {
      backgroundColor: colors.danger,
    },
    wsBadgeText: {
      fontSize: fontSize.xs,
      fontWeight: fontWeight.bold,
    },
    wsBadgeTextOnline: {
      color: colors.success,
    },
    wsBadgeTextOffline: {
      color: colors.danger,
    },
    routeControlsRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    viewModeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      borderRadius: borderRadius.lg,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      gap: spacing.sm,
    },
    viewModeButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      ...shadows.colored(colors.primaryDark),
    },
    viewModeText: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: colors.textSecondary,
    },
    viewModeTextActive: {
      color: colors.textLight,
    },
    map: {
      flex: 1,
    },
    listView: {
      flex: 1,
    },
    listContent: {
      padding: spacing.lg,
      paddingBottom: spacing.xxxl,
    },
    statusCard: {
      marginBottom: spacing.lg,
      marginVertical: spacing.sm,
    },
    statusHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    statusIndicator: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    statusName: {
      flex: 1,
      fontSize: fontSize.base,
      fontWeight: fontWeight.bold,
      color: colors.text,
    },
    statusCount: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.extrabold,
      color: colors.primary,
    },
    driversCard: {
      marginTop: spacing.sm,
      marginVertical: spacing.sm,
    },
    cardTitle: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.extrabold,
      color: colors.text,
      marginBottom: spacing.md,
      letterSpacing: -0.2,
    },
    helperText: {
      marginTop: 6,
      fontSize: fontSize.sm,
      color: colors.textTertiary,
      lineHeight: 18,
    },
    driverItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    driverInfo: {
      flex: 1,
    },
    driverName: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: 4,
    },
    driverPhone: {
      fontSize: fontSize.sm,
      color: colors.textTertiary,
      marginBottom: spacing.sm,
    },
    orderBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.md,
    },
    orderBadgeText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
    },
    emptyText: {
      fontSize: fontSize.base,
      color: colors.textTertiary,
      textAlign: 'center',
      paddingVertical: spacing.xl,
    },
    markerContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.textLight,
      ...shadows.md,
    },
    clusterCountText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.extrabold,
      color: colors.textLight,
    },
    exceptionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
      gap: spacing.sm,
    },
    suggestedItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
      gap: spacing.sm,
    },
    suggestedInfo: {
      flex: 1,
    },
    suggestedDriverText: {
      fontSize: fontSize.sm,
      color: colors.textSecondary,
      marginTop: 4,
    },
    recommendedActionsWrap: {
      marginTop: spacing.sm,
      gap: 4,
    },
    recommendedActionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    recommendedActionText: {
      flex: 1,
      fontSize: fontSize.sm,
      color: colors.primary,
      fontWeight: fontWeight.semibold,
    },
    quickActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: spacing.sm,
    },
    exceptionIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    exceptionInfo: {
      flex: 1,
    },
    exceptionTitle: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    exceptionText: {
      fontSize: fontSize.sm,
      color: colors.textSecondary,
      marginTop: 4,
      lineHeight: 18,
    },
    exceptionActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: spacing.sm,
    },
    exceptionActionBtn: {
      paddingHorizontal: spacing.md,
      paddingVertical: 6,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: `${colors.primary}22`,
    },
    exceptionActionBtnDisabled: {
      opacity: 0.5,
    },
    exceptionActionText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    actionDoneBadge: {
      marginTop: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'flex-start',
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: borderRadius.md,
      backgroundColor: colors.successGlow,
    },
    actionDoneText: {
      fontSize: fontSize.xs,
      fontWeight: fontWeight.bold,
      color: colors.success,
    },
  });
}
