from django.urls import path
from .views import (
    OrderListView,
    OrderDetailView,
    OrderStartView,
    OrderDepartView,
    OrderStopView,
    OrderCompleteView,
    OrderRejectView,
    OrderCancelView,
    OrderTrackView,
    OrderUpdateLocationView,
    OrderApproveByClientView,
    OrderDeclineByClientView,
    OrderMarkDriverPaymentView,
    OrderConfirmClientPaymentView,
    OrderConfirmDeliveryView,
    DriverStatisticsView,
    ClientStatisticsView,
    OrderVerifyByQRView,
    OrderVerifyAndApproveByQRView,
    OrderRoutePlanView,
    OrderProofOfDeliveryCreateView,
    OrderReturnQualityView,
    OrderTrackingShareLinkCreateView,
    PublicOrderTrackingShareView,
)
from .feature_views import (
    OrderCustodyChainView,
    OrderSOSTriggerView,
    OrderSOSAcknowledgeView,
    OrderSOSResolveView,
    ActiveSOSAlertsView,
)
from .document_views import (
    OrderDocumentListView,
    OrderDocumentGenerateView,
    OrderDocumentDownloadView,
    PublicOrderDocumentView,
)
from .route_views import (
    OrderRouteStopListView,
    OrderRouteStopDetailView,
    OrderRouteStopCompleteView,
    OrderRouteOptimizeView,
)

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='list'),
    path('<int:pk>/', OrderDetailView.as_view(), name='detail'),
    path('<int:pk>/start/', OrderStartView.as_view(), name='start'),
    path('<int:pk>/depart/', OrderDepartView.as_view(), name='depart'),
    path('<int:pk>/approve/', OrderApproveByClientView.as_view(), name='approve'),
    path('<int:pk>/decline/', OrderDeclineByClientView.as_view(), name='decline'),
    path('<int:pk>/mark-driver-payment/', OrderMarkDriverPaymentView.as_view(), name='mark-driver-payment'),
    path('<int:pk>/confirm-client-payment/', OrderConfirmClientPaymentView.as_view(), name='confirm-client-payment'),
    path('<int:pk>/confirm-delivery/', OrderConfirmDeliveryView.as_view(), name='confirm-delivery'),
    path('<int:pk>/stop/', OrderStopView.as_view(), name='stop'),
    path('<int:pk>/complete/', OrderCompleteView.as_view(), name='complete'),
    path('<int:pk>/reject/', OrderRejectView.as_view(), name='reject'),
    path('<int:pk>/cancel/', OrderCancelView.as_view(), name='cancel'),
    path('<int:pk>/track/', OrderTrackView.as_view(), name='track'),
    path('<int:pk>/update-location/', OrderUpdateLocationView.as_view(), name='update-location'),
    path('<int:pk>/route-plan/', OrderRoutePlanView.as_view(), name='route-plan'),
    path('<int:pk>/route-stops/', OrderRouteStopListView.as_view(), name='route-stops'),
    path('<int:pk>/route-stops/<int:stop_id>/', OrderRouteStopDetailView.as_view(), name='route-stop-detail'),
    path('<int:pk>/route-stops/<int:stop_id>/complete/', OrderRouteStopCompleteView.as_view(), name='route-stop-complete'),
    path('<int:pk>/route-optimize/', OrderRouteOptimizeView.as_view(), name='route-optimize'),
    path('<int:pk>/proof-of-delivery/', OrderProofOfDeliveryCreateView.as_view(), name='proof-of-delivery'),
    path('<int:pk>/return-quality/', OrderReturnQualityView.as_view(), name='return-quality'),
    path('<int:pk>/share-link/', OrderTrackingShareLinkCreateView.as_view(), name='share-link'),
    path('share/<uuid:token>/', PublicOrderTrackingShareView.as_view(), name='share-public'),
    path('documents/public/<uuid:token>/', PublicOrderDocumentView.as_view(), name='document-public'),
    path('<int:pk>/documents/', OrderDocumentListView.as_view(), name='documents'),
    path('<int:pk>/documents/generate/', OrderDocumentGenerateView.as_view(), name='documents-generate'),
    path('<int:pk>/documents/<str:doc_type>/', OrderDocumentDownloadView.as_view(), name='document-download'),
    path('<int:pk>/custody-chain/', OrderCustodyChainView.as_view(), name='custody-chain'),
    path('<int:pk>/sos/', OrderSOSTriggerView.as_view(), name='sos-trigger'),
    path('<int:pk>/sos/acknowledge/', OrderSOSAcknowledgeView.as_view(), name='sos-acknowledge'),
    path('<int:pk>/sos/resolve/', OrderSOSResolveView.as_view(), name='sos-resolve'),
    path('sos/active/', ActiveSOSAlertsView.as_view(), name='sos-active'),
    path('statistics/driver/', DriverStatisticsView.as_view(), name='driver-statistics'),
    path('statistics/client/', ClientStatisticsView.as_view(), name='client-statistics'),
    path('verify-qr/', OrderVerifyByQRView.as_view(), name='verify-qr'),
    path('verify-qr-approve/', OrderVerifyAndApproveByQRView.as_view(), name='verify-qr-approve'),
]

