# Generated by Django 4.2.7 on 2026-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payments_user_id_79e880_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum'), ('mock', 'Mock (development)')], max_length=10),
        ),
    ]
