# Generated by Django 4.2.7 on 2026-08-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_live_motion_fields'),
        ('ratings', '0004_complaints_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_company_payout_features'),
        ('payments', '0005_add_mock_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('legacy_seeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='OrderEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('funded', 'Funded'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='empty', max_length=20)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released_to_driver', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order')),
            ],
            options={
                'db_table': 'order_escrows',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('legacy_seed', 'Legacy seed'), ('escrow_fund', 'Escrow fund'), ('escrow_release', 'Escrow release'), ('commission', 'Platform commission'), ('cancellation_fee', 'Cancellation fee'), ('refund', 'Refund'), ('dispute_hold', 'Dispute hold'), ('dispute_release', 'Dispute release'), ('payout_reserve', 'Payout reserve'), ('payout_reject', 'Payout reject')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('held_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ratings.complaint')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='users.driverpayoutrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, help_text='Null = platform ledger (commission)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payments.wallet')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ledger_entr_user_id_b2381a_idx'), models.Index(fields=['order', 'entry_type'], name='ledger_entr_order_i_bc752f_idx'), models.Index(fields=['entry_type', 'created_at'], name='ledger_entr_entry_t_bfe8a8_idx')],
            },
        ),
    ]
