# Generated by Django 5.2.17 on 2026-08-25

import decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_fee_settings(apps, schema_editor):
    FeeSettings = apps.get_model('payments', 'OrderCompletionFeeSettings')
    FeeSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_rename_order_custo_order_i_6f0a2a_idx_order_custo_order_i_940b0c_idx_and_more'),
        ('payments', '0006_wallet_escrow_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompletionFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('client_fee_enabled', models.BooleanField(default=True)),
                ('driver_fee_enabled', models.BooleanField(default=True)),
                ('client_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0'))])),
                ('driver_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0'))])),
                ('currency', models.CharField(choices=[('UZS', "UZS (so'm)")], default='UZS', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order completion fee settings',
                'verbose_name_plural': 'Order completion fee settings',
                'db_table': 'order_completion_fee_settings',
            },
        ),
        migrations.CreateModel(
            name='OrderCompletionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('driver', 'Driver')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived by admin')], default='pending', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_fees', to='orders.order')),
                ('paid_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_completion_fee', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_completion_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order completion fee',
                'verbose_name_plural': 'Order completion fees',
                'db_table': 'order_completion_fees',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='completion_user_status_idx'),
                    models.Index(fields=['order', 'role'], name='completion_order_role_idx'),
                    models.Index(fields=['status', 'created_at'], name='completion_status_created_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('order', 'role'), name='unique_completion_fee_order_role'),
                    models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='completion_fee_amount_positive'),
                ],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='completion_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.ordercompletionfee'),
        ),
        migrations.RunPython(create_default_fee_settings, migrations.RunPython.noop),
    ]
