# Generated by Django 4.2.7 on 2026-01-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proposed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('client_phone', models.CharField(max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rejected_by_driver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Execution',
                'verbose_name_plural': 'Advertisement Executions',
                'db_table': 'advertisement_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
