# Generated by Django 4.2.7 on 2026-01-06 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementexecution',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementexecution',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_advertisements', to='locations.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='departure_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_advertisements', to='locations.country'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_advertisements', to='locations.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_advertisements', to='locations.country'),
        ),
    ]
