# Generated by Django 4.2.7 on 2026-01-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_remove_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_uz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_uz',
            field=models.CharField(max_length=200),
        ),
    ]
