/** Backend `Notification.NOTIFICATION_TYPES` bilan mos ro'yxat. */
export const NOTIFICATION_TYPE_KEYS = [
  'order_created',
  'order_accepted',
  'order_approved',
  'order_started',
  'order_in_transit',
  'order_completed',
  'stop_alert',
  'route_deviation',
  'order_cancelled',
  'payment_received',
  'driver_assigned',
  'message_received',
  'rating_received',
  'geofence_event',
  'document_expiry',
  'bid_received',
  'route_stop_arrived',
  'route_stop_completed',
  'driver_verification_pending',
  'vehicle_verification_pending',
  'driver_verification_approved',
  'driver_verification_rejected',
  'vehicle_verification_approved',
  'vehicle_verification_rejected',
  'driver_sos',
  'driver_arriving',
  'saved_search_match',
  'driver_load_offer',
  'complaint_filed',
  'system',
] as const;

export type NotificationTypeKey = (typeof NOTIFICATION_TYPE_KEYS)[number];
