# Generated by Django 4.2.7 on 2026-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='last_counter_by',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
